# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 17:16
from __future__ import unicode_literals

from django.db import migrations
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20160706_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='line_up',
            field=form.models.SeparatedValuesField(default=1),
            preserve_default=False,
        ),
    ]
