# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20160706_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='source',
            field=models.CharField(default='0000000', max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='source_id',
            field=models.CharField(default='0000000', max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='line_up',
            field=models.CharField(default='0000000', max_length=10000),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
