# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_events_line_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='name',
        ),
    ]
